let cars = [{
        name: "BMW",
        model: "X5",
        year: 2010,
        price: 50000,
        rented: false,
        photo: '../assets/x5_car.jpg'
    },
    {
        name: "BMW",
        model: "X5",
        year: 2010,
        price: 50000,
        rented: false,
        photo: '../assets/x5_car.jpg'
    }, {
        name: "BMW",
        model: "X5",
        year: 2010,
        price: 50000,
        rented: false,
        photo: '../assets/x5_car.jpg'
    }, {
        name: "BMW",
        model: "X5",
        year: 2010,
        price: 50000,
        rented: false,
        photo: '../assets/x5_car.jpg'
    }, {
        name: "BMW",
        model: "X5",
        year: 2010,
        price: 50000,
        rented: false,
        photo: '../assets/x5_car.jpg'
    }, {
        name: "BMW",
        model: "X5",
        year: 2010,
        price: 50000,
        rented: false,
        photo: '../assets/x5_car.jpg'
    }, {
        name: "BMW",
        model: "X5",
        year: 2010,
        price: 50000,
        rented: false,
        photo: '../assets/x5_car.jpg'
    }, {
        name: "BMW",
        model: "X5",
        year: 2010,
        price: 50000,
        rented: false,
        photo: '../assets/x5_car.jpg'
    }, {
        name: "BMW",
        model: "X5",
        year: 2010,
        price: 50000,
        rented: false,
        photo: '../assets/x5_car.jpg'
    },
]